ref #187 Include requestAuthorization in Skygear Push Basics
SkygearIO/guides pull request #223
Opened 2018-04-25 07:18 UTC by david90

Added a guide on iOS specific push set up about `requestAuthorization` for displaying push notifications.

2018-04-26 11:08 UTC, carmenlau requested changes
Thanks a lot!! @david90

2018-04-26 11:08 UTC, carmenlau commented on push-notifications/basics/ios.md
> +	}];
Please fix the indention.

2018-04-26 11:08 UTC, carmenlau commented on push-notifications/basics/ios.md
> +
I found that the code is quite duplicate from the above section, excepts adding `requestAuthorizationWithOptions` call. Do you think we just update the first block of sample code?

2018-04-26 11:08 UTC, carmenlau commented on push-notifications/basics/ios.md
> +
It would be better the swift version should be the same as obj-c version.

2018-04-27 07:05 UTC, david90 commented
@carmenlau  Updated!

2018-04-27 07:14 UTC, carmenlau requested changes

2018-04-27 07:14 UTC, carmenlau commented on push-notifications/basics/ios.md
> +    // Enable or disable features based on authorization
Missing closing `}` for `requestAuthorization`, and please update the identical. Other looks fine for me, thanks @david90

2018-05-02 07:10 UTC, david90 commented
updated

2018-05-02 07:17 UTC, merged

2018-05-02 07:17 UTC, carmenlau commented
Thanks @david90!