Update doc for more lambda types
SkygearIO/guides pull request #233
Opened 2018-05-08 07:47 UTC by cheungpat

connects #218

2018-05-22 15:41 UTC, carmenlau requested changes

2018-05-22 15:41 UTC, carmenlau commented on cloud-function/lambda/js.md
> +  var keyword = param['keyword']; // a String
For getting the request params, we need `param['args']['current']`

2018-05-23 03:11 UTC, cheungpat commented on cloud-function/lambda/js.md
> +  var keyword = param['keyword']; // a String
Is that right? This would be a bug on the JS SDK part.

2018-05-23 03:23 UTC, cheungpat commented
@carmenlau updated. thanks.

2018-05-23 03:32 UTC, merged