Added more details to cloud basics and changed format of the quick start guide
SkygearIO/guides pull request #89
Opened 2017-07-18 04:00 UTC by xiuwenlu

2017-07-18 08:31 UTC, xiuwenlu commented
@tensiuyan okay finally it's ready.. lol sorry

2017-07-21 03:26 UTC, tensiuyan requested changes

2017-07-21 03:26 UTC, tensiuyan commented on cloud-db/basics/js.md
> +  // In SQL language, this creates a new table in the database named 'note'. You can use 'Note' to refer the 'note' table aka record type.
@xiuwenlu Please remove "In SQL language, this creates a new table in the database named 'note'.". The development team thinks when explaining the APIs, we should use only Skygear language to avoid confusion.

2017-07-21 03:26 UTC, tensiuyan commented on cloud-db/basics/js.md
> +Here we created a new record in the 'Note' table and under the 'content' column, we added the record value: 'Hello World!'. Your data browser should look similar to the following, but with the 'Note'
@xiuwenlu same as above. Please say record type instead of table.

2017-08-01 09:48 UTC, Steven-Chan commented
@xiuwenlu @tensiuyan https://chris.beams.io/posts/git-commit/

2017-08-01 09:48 UTC, Steven-Chan approved these changes

2017-08-01 09:48 UTC, tensiuyan approved these changes

2017-08-01 09:52 UTC, merged